### ISSUE TITLE
Content Security Police conflict

### ISSUE THREAD

**Issue by li0t** [FinalDevStudio/final-issues#12]
The browser console displays the following error after implementing `fi-security` module.

![errorlog](https://cloud.githubusercontent.com/assets/7966280/12280563/a34cc76c-b96d-11e5-8c53-b67ab0eb643c.png)

**Comment by stgogm** [comment]
When implementing the **fi-security** it's necessary to define and allow any external sites that might be used in the `csp` section of the security configuration:

**server/config/security.js**
```js
//...

  csp: {
    policy: {
      'style-src': "*.googleapis.com 'self'",
      'font-src': "*.gstatic.com 'self'",
      'default-src': "'self'"
    }
  }

//...
```

Also, with AngularJS you must add the `angular-csp.css` stylesheet included in the AngularJS' bower package and add the `ng-csp` directive to the `html` element.

* https://docs.angularjs.org/api/ng/directive/ngCsp
* https://developer.mozilla.org/en-US/docs/Web/Security/CSP

While in development it's recommended to deactivate the CSP policy by commenting the property in the security configuration.
