### ISSUE TITLE
Can't add issue

### ISSUE THREAD

**Issue by jtguzman** [FinalDevStudio/final-issues#14]
When pressing the add issue button, the screen flashes the form, but goes back to the "add issue" page.

**Comment by li0t** [comment]
Are there any error logs displayed in the browser console or CLI?

**Comment by jtguzman** [comment]
![final-issues- 14](https://cloud.githubusercontent.com/assets/3739603/12462694/7b06a5a2-bf9e-11e5-9dc9-6f500140e409.png)
![final-issues- 14-2](https://cloud.githubusercontent.com/assets/3739603/12462695/7bb9efe0-bf9e-11e5-99e7-1fd4d493c7b3.png)
![final-issues- 14-3](https://cloud.githubusercontent.com/assets/3739603/12462696/7ce10dcc-bf9e-11e5-8902-bf713f761586.png)

**Comment by jtguzman** [comment]
With the latest commit, if I try to add an Issue, a project or a client, the site sends me back to /users/sign-in

with no possibility to sign-in again

Terminal shows: GET /api/session 304 0.966 ms - -
Console shows: 
```
XHR finished loading: POST "http://localhost:3015/api/users/sign-in".(anonymous function)
@ angular.js:10765sendReq @ angular.js:10558
serverRequest @ angular.js:10268
processQueue @ angular.js:14792
(anonymous function) @ angular.js:14808
Scope.$eval @ angular.js:16052Scope.$digest @ angular.js:15870
Scope.$apply @ angular.js:16160
(anonymous function) @ angular.js:23618
jQuery.event.dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121
angular.js:10765 

XHR finished loading: GET "http://localhost:3015/api/session".
```

**Comment by li0t** [comment]
Problem should be solved in last commit.
