### ISSUE TITLE
Simple issue form

### ISSUE THREAD

**Issue by jtguzman** [FinalDevStudio/final-issues#3]
[formulario.zip](https://github.com/FinalDevStudio/final-issues/files/67512/formulario.zip)

The following Zip file has a template of how the issue form should be like.
A this time, the main objetvive is to:

* send an email to savina-support@final.cl if the issue is for Savina, or to misalud-support@final.cl if the issue is for Mi Salud.
* Save and send attachments.

**Comment by li0t** [comment]
In the Issue schema is defined a "statuses" attribute.
What is it's purpose, why is an array and what is it's first value?

**Comment by li0t** [comment]
Is the creator of an issue , an "in session" user?

**Comment by stgogm** [comment]
0. The [statuses] attributes must register every status that was assigned to the issue. Probably it can be optimized by also adding the Date it was assigned.

0. The users must be logged in to be able to create an issue.

**Comment by li0t** [comment]
Understood

**Comment by stgogm** [comment]
![kmfwaqi](https://cloud.githubusercontent.com/assets/2774311/11962926/25f83550-a8c2-11e5-9a5c-771fa730ac67.gif)

**Comment by li0t** [comment]
Are both Savina and Mi Salud Saydex projects right?

**Comment by jtguzman** [comment]
Yes, Savina Admin is a different project too.

**Comment by li0t** [comment]
Ok.

- What email subject and content is required for a new issue?
- Who is the email sender?  noreply@savina.cl?
- Is there a different email box for Savina Admin issues?
