### ISSUE TITLE
Issue attachment type

### ISSUE THREAD

**Issue by li0t** [FinalDevStudio/final-issues#9]
What is the purpose of it?
How many attachments an issue may have?

**Comment by stgogm** [comment]
Issue attachments may be unlimited and must be screenshots, debugs, console outputs, etc.

**Comment by li0t** [comment]
Yeah, but why define an attachament's type?

**Comment by stgogm** [comment]
Maybe @jtguzman can clarify?

**Comment by jtguzman** [comment]
To lead the customer on what he has to attach and make it easier for our developer and customer service team know what to ask for.
